import type { NextPage } from "next";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";

import styles from "../styles/Home.module.scss";
import { Suspense, useRef } from "react";
import { Sky } from "@react-three/drei";
import ThreeJS from "../component/Threejs";
import { LILPACamera } from "component/LILPACamera/indes";

const Home: NextPage = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  // const renderer = window ? new THREE.WebGLRenderer() : null;

  // useEffect(() => {
  //   if (!renderer) return;

  //   const fbxLoader = new FBXLoader();
  //   const scene = new THREE.Scene();
  //   const light = new THREE.PointLight();

  //   const camera = new THREE.PerspectiveCamera(
  //     75,
  //     window.innerWidth / window.innerHeight,
  //     0.1,
  //     1000
  //   );
  //   renderer.setSize(window.innerWidth, window.innerHeight);

  //   const resizeHandler = () => {
  //     camera.position.set(0.8, 1.4, 1.0);
  //     light.position.set(0.8, 1.4, 1.0);
  //     scene.add(light);

  //     fbxLoader.load("/model/lilpa.fbx", (object: any) => {
  //       scene.add(object);
  //     });

  //     renderer.render(scene, camera);
  //   };

  //   window.addEventListener("resize", resizeHandler);

  //   return () => {
  //     window.removeEventListener("resize", resizeHandler);
  //   };
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>fbx loader test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <Canvas ref={canvasRef} frameloop="always" performance={{ min: 0.5 }}>
          <LILPACamera />
          <Sky
            distance={450000}
            sunPosition={[0, 0, 300]}
            inclination={0}
            azimuth={0.25}
          />
          <ambientLight intensity={0.1} />
          <pointLight position={[0, 0, 300]} />
          <Suspense fallback={null}>
            <ThreeJS canvasRef={canvasRef} />
          </Suspense>
        </Canvas>
      </div>
    </div>
  );
};

export default Home;
