import type { NextPage } from "next";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";

import styles from "../styles/Home.module.scss";
import { Suspense, useRef } from "react";
import { Sky } from "@react-three/drei";
import ThreeJS from "../component/Threejs";
import { LILPACamera } from "component/LILPACamera/indes";

const Home: NextPage = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  return (
    <div className={styles.container}>
      <Head>
        <title>fbx loader test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <Canvas ref={canvasRef} frameloop="always" performance={{ min: 0.5 }}>
          <LILPACamera />
          <Sky
            distance={450000}
            sunPosition={[0, 0, 300]}
            inclination={0}
            azimuth={0.25}
          />
          <ambientLight intensity={0.1} />
          <pointLight position={[0, 0, 300]} />
          <Suspense fallback={null}>
            <ThreeJS canvasRef={canvasRef} />
          </Suspense>
        </Canvas>
      </div>
    </div>
  );
};

export default Home;
